url: https://suzeshardlow.com

permalink: pretty

collections:
  posts:
    permalink: /blog/:categories/:year/:month/:day/:title/
  coding_projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author:
        name: "Suze Shardlow"
        twitter: "@SuzeShardlow"
  - scope:
      path: ""
      type: "coding_projects"
    values:
      layout: "coding_project"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Plugin
twitter:
  username: SuzeShardlow
  card: summary
author: "@SuzeShardlow"
tagline: Suze Shardlow's personal website.
lang: en_UK
