url: https://suze.dev

name: suze.dev

description: Suze Shardlow's personal website.

permalink: pretty

collections:
  about:
    output: true
    permalink: /:title
  posts:
    permalink: /blog/:title/
  public_speaking:
    output: false
  coding_projects:
    output: true
  sketchnotes:
    permalink: /sketchnotes/:title/
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author:
        name: "Suze Shardlow"
        twitter: "@SuzeShardlow"
  - scope:
      path: ""
      type: "coding_projects"
    values:
      layout: "coding_project"
  - scope:
      path: ""
      type: "sketchnotes"
    values:
      layout: "sketchnote"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO Plugin
twitter:
  username: SuzeShardlow
  card: summary_large_image
author: "@SuzeShardlow"
tagline: Suze Shardlow's personal website.
lang: en_UK
